### ISSUE TITLE
Spring JDBC/JDBC Template 

### ISSUE THREAD

**Issue by sunilgowda67** [Nuthan12/RETAIL_DELIGHT_FINAL_VERSION#6]
JDBC Implementations are not used (if it is used mention the class names as response )

**Comment by Nuthan12** [comment]
We have written SQL Queries in DAO classes

**Comment by Nuthan12** [comment]
JDBC has been implemented in Order DAO class for finding max order number

**Comment by sunilgowda67** [comment]
As you have implemented private method , would like to know where exactly this method have been used in the project.

**Comment by sanjay6410** [comment]
while saving the new order in the database first we are fetching the max order number existing in database and then after incrementing by 1 we are assigning the next order number to the customer and we are using in same class for method save order

**Comment by sunilgowda67** [comment]
Closed
