### ISSUE TITLE
DAO

### ISSUE THREAD

**Issue by sunilgowda67** [Nuthan12/RETAIL_DELIGHT_FINAL_VERSION#7]
Auto wiring of DAO still exists in Controllers

**Comment by Nuthan12** [comment]
Since we have written SQL Queries in DAO, In controllers we are using them in methods to work with the Object. So we have used Autowired for DAO classes in Controllers

**Comment by Nuthan12** [comment]
Auto wiring of DAO has been removed in Controllers and Service Classes has been created

**Comment by sunilgowda67** [comment]
Closed
